import { bootApi } from './api'

const {
  API_PORT,
  CONTRACT_PROXY_PORT,
  EXECUTION_SERVICE_URI,
  CONTRACT_SERVER_LOWER_PORT_BOUND,
  CONTRACT_SERVER_UPPER_PORT_BOUND,
  STATIC_API_URI
} = process.env

if (
  !API_PORT ||
  !CONTRACT_PROXY_PORT ||
  !EXECUTION_SERVICE_URI ||
  !CONTRACT_SERVER_LOWER_PORT_BOUND ||
  !CONTRACT_SERVER_UPPER_PORT_BOUND ||
  !STATIC_API_URI
) {
  throw new Error('Required ENVs not set')
}

bootApi(Number(API_PORT))
