version: '3.7'
services:
  server:
    build:
      context: .
      target: server
    init: true
    environment:
      - API_PORT=8081
      - WALLET_SERVICE_URI=http://wallet:0000
      - EXECUTION_SERVICE_URI=http://execution_service:9000
      - CONTRACT_DIRECTORY=/application/bundles
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - OPERATION_MODE=distributed
    volumes:
    #   - ./dist/server:/application/dist/server
      - ./test/bundles/docker:/application/bundles
    ports:
      - 8081:8081
      - 8082:8082
    depends_on:
      - execution_service
  execution_service:
    build:
      context: .
      target: execution_service
    init: true
    environment:
      - EXECUTION_API_PORT=9000
      - CONTAINER_LOWER_PORT_BOUND=11000
      - CONTAINER_UPPER_PORT_BOUND=12000
      - DOCKER_EXECUTION_ENGINE_CONTEXT=docker
      - EXECUTION_ENGINE=docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - ./dist/swagger.json:/application/dist/swagger.json
      # - ./dist/execution_service:/application/dist/execution_service
    ports:
      - 9000:9000
  redis:
    image: redis:5.0.4
    ports:
     - 6379:6380
