version: '3.7'
services:
  smart_contract_backend_e2e_test:
    build:
      context: .
      target: test
    init: true
    environment:
      - APPLICATION_URI=http://server:8081
      - WS_URI=ws://server:8079/graphql