version: '3.7'
services:
  server:
    build:
      context: .
      target: server
    init: true
    environment:
      - API_PORT=8079
      - CONTRACT_PROXY_PORT=8081
      - EXECUTION_SERVICE_URI=http://docker_execution:9000
      - CONTRACT_SERVER_LOWER_PORT_BOUND=10000
      - CONTRACT_SERVER_UPPER_PORT_BOUND=10999
    volumes:
      - ./dist/server:/application/dist/server
    ports:
      - 8079:8079
      - 8081:8081
      - 8082:8082
  docker_execution:
    build:
      context: .
      target: docker_execution
    init: true
    environment:
      - DOCKER_EXECUTION_API_PORT=9000
      - CONTAINER_LOWER_PORT_BOUND=11000
      - CONTAINER_UPPER_PORT_BOUND=12000
      - RUNTIME=docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dist/swagger.json:/application/dist/swagger.json
      - ./dist/execution_engines/docker:/application/dist/execution_engines/docker
    ports:
      - 9000:9000
  bundle_server:
    build:
      context: .
      target: bundle_server
    init: true
    environment:
      - BUNDLE_SERVER_PORT=9001
    volumes:
      - ./test/bundles:/application/bundles
      - ./dist/bundle_server:/application/dist/bundle_server
    ports:
      - 9001:9001