version: '3.7'
services:
  server:
    build:
      context: .
      target: server
    init: true
    environment:
      - API_PORT=8079
      - CONTRACT_PROXY_PORT=8081
      - STATIC_API_URI=http://localhost:8079
      - WALLET_SERVICE_URI=http://wallet:0000
      - EXECUTION_SERVICE_URI=http://docker_execution:9000
      - CONTRACT_SERVER_LOWER_PORT_BOUND=8082
      - CONTRACT_SERVER_UPPER_PORT_BOUND=8900
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    # volumes:
    #   - ./dist/server:/application/dist/server
    ports:
      - 8079:8079
      - 8081:8081
      - 8082:8082
  docker_execution:
    build:
      context: .
      target: docker_execution
    init: true
    environment:
      - EXECUTION_API_PORT=9000
      - CONTAINER_LOWER_PORT_BOUND=11000
      - CONTAINER_UPPER_PORT_BOUND=12000
      - DOCKER_EXECUTION_ENGINE_CONTEXT=docker
      - EXECUTION_ENGINE=docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - ./dist/swagger.json:/application/dist/swagger.json
      # - ./dist/execution_engines:/application/dist/execution_engines
    ports:
      - 9000:9000
  bundle_server:
    build:
      context: .
      target: bundle_server
    init: true
    environment:
      - BUNDLE_SERVER_PORT=9001
      - BUNDLE_LOCATION=bundles
    volumes:
      - ./test/bundles:/application/bundles
      # - ./dist/bundle_server:/application/dist/bundle_server
    ports:
      - 9001:9001
  redis:
    image: redis:5.0.4
    ports:
     - 6379:6380